chore: check frontend image

diff --git a/.github/workflows/cicd-pull-request.yml b/.github/workflows/cicd-pull-request.yml
--- a/.github/workflows/cicd-pull-request.yml
+++ b/.github/workflows/cicd-pull-request.yml
@@ -72,7 +72,18 @@ jobs:
       BUILDX_PLATFORMS: "linux/amd64"
       DOCKERFILE_PATH: "./Dockerfile"
       PYTHON_VERSION: "3.11"
-      POETRY_VERSION: "1.6.1"
+    secrets: inherit
+
+  check-frontend-image:
+    name: check frontend image
+    needs: trigger-mode
+    if: contains(needs.trigger-mode.outputs.trigger-mode, '[frontend]')
+    uses: apecloud/apecloud-cd/.github/workflows/release-image-check.yml@v0.1.49
+    with:
+      IMG: "apecloud/aperag-frontend"
+      BUILDX_PLATFORMS: "linux/amd64"
+      DOCKERFILE_PATH: "./frontend/Dockerfile"
+      PYTHON_VERSION: "3.11"
     secrets: inherit
 
   check-helm:
@@ -89,7 +100,7 @@ jobs:
 
   pr-check:
     name: make test
-    needs: [ trigger-mode, make-test, check-image, check-helm ]
+    needs: [ trigger-mode, make-test, check-image, check-frontend-image, check-helm ]
     if: ${{ github.event.review.state == 'approved' && always() }}
     runs-on: ubuntu-latest
     steps:
@@ -104,6 +115,13 @@ jobs:
       - name: release image check
         run: |
           if [[ "${{ needs.check-image.result }}" == "failure" || "${{ needs.check-image.result }}" == "cancelled" ]]; then
+              echo "release image fail"
+              exit 1
+          fi
+
+      - name: release frontend image check
+        run: |
+          if [[ "${{ needs.check-frontend-image.result }}" == "failure" || "${{ needs.check-frontend-image.result }}" == "cancelled" ]]; then
               echo "release image fail"
               exit 1
           fi
